project: OnlinePaymentsExample.xcodeproj
schemes:
- OnlinePaymentsExample
targets:
- OnlinePaymentsExample
clean_build: true
build_arguments:
- -destination
- platform="iOS Simulator,name=iPhone 14,OS=16.0"

